name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'  

      - name: Build website
        run: |
          cd client
          npm install --omit=dev 
          npm run build
          rm ../server/site
          mv build ../server/site

      - name: Build server
        run: |
          cd server
          npm install
          npm run build

      - name: Commit changes
        run: |
          git add -A
          git diff-index --quiet HEAD || git commit -m 'Deploy ${{ github.sha }}'
          git push 
          
      