name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build website
        run: |
          cd client
          npm install --force
          npm run build
          rm -r ../server/build
          mv build ../server/build

      - name: Commit changes
        run: |
          git add -A
          git diff-index --quiet HEAD || git commit -m 'Deploy ${{ github.sha }}'
          git push 
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: server/build
      